# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=255)),
                ('artist', models.CharField(blank=None, max_length=255)),
                ('lyrics', models.TextField(blank=None)),
                ('chords', models.TextField(blank=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
